#!/usr/bin/env bash

## Copyright (C) 2020-2021 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

DIR="$HOME/.config"

rofi_command="rofi -theme $DIR/rofi/powermenu.rasi"

uptime=$(uptime -p | sed -e 's/up //g')

# Options
shutdown="  Shut Down"
reboot="  Reboot"
lock="  Lock"
suspend="  Suspend"
logout="  Logout"

# Variable passed to rofi
options="$shutdown\n$reboot\n$lock\n$logout"
_msg="Options  -  yes / y / no / n"

chosen="$(echo -e "$options" | $rofi_command -p "UP - $uptime" -dmenu -selected-row 2)"
case $chosen in
    $shutdown)
		ans=$($HOME/.config/rofi/scripts/confirm &)
		if [[ $ans == "yes" ]] || [[ $ans == "YES" ]] || [[ $ans == "y" ]] || [[ $ans == "Y" ]]; then
			systemctl poweroff
		elif [[ $ans == "no" ]] || [[ $ans == "NO" ]] || [[ $ans == "n" ]] || [[ $ans == "N" ]]; then
			exit
        else
			sh $HOME/.config/rofi/scripts/confirm
        fi
        ;;
    $reboot)
		ans=$($HOME/.config/rofi/scripts/confirm &)
		if [[ $ans == "yes" ]] || [[ $ans == "YES" ]] || [[ $ans == "y" ]] || [[ $ans == "Y" ]]; then
			systemctl reboot
		elif [[ $ans == "no" ]] || [[ $ans == "NO" ]] || [[ $ans == "n" ]] || [[ $ans == "N" ]]; then
			exit
        else
			sh $HOME/.config/rofi/scripts/confirm
        fi
        ;;
    $lock)
        ~/.config/i3lock/i3lock.sh
        ;;
    $suspend)
		ans=$($HOME/.config/rofi/scripts/confirm &)
		if [[ $ans == "yes" ]] || [[ $ans == "YES" ]] || [[ $ans == "y" ]] || [[ $ans == "Y" ]]; then
			mpc -q pause
			amixer set Master mute
			betterlockscreen --suspend
		elif [[ $ans == "no" ]] || [[ $ans == "NO" ]] || [[ $ans == "n" ]] || [[ $ans == "N" ]]; then
			exit
        else
			sh $HOME/.config/rofi/scripts/confirm
        fi
        ;;
    $logout)
		ans=$($HOME/.config/rofi/scripts/confirm &)
		if [[ $ans == "yes" ]] || [[ $ans == "YES" ]] || [[ $ans == "y" ]] || [[ $ans == "Y" ]]; then
			i3-msg exit
		elif [[ $ans == "no" ]] || [[ $ans == "NO" ]] || [[ $ans == "n" ]] || [[ $ans == "N" ]]; then
			exit
        else
			sh $HOME/.config/rofi/scripts/confirm
        fi
        ;;
esac
